In [17]:
import pandas as pd

In [18]:
planilha = r"C:\Users\Orçamento\OneDrive - GRUPO RETEC\02. Engenharia\Dep. Orçamentos\POWERBI\AUTOMAÇÃO RD\negociacoes_2025.xlsx"

df = pd.read_excel(planilha)

In [19]:
colunas_corrigidas = [
    "id", "name", "amount_total", "amount_unique", "markup",
    "created_at", "closed_at","deal_custom_fields", "last_activity_at",
    "interactions", "win", "deal_stage.name", "user.id", "user.name",
    "deal_lost_reason.name"
]

df_analise = df[colunas_corrigidas].copy()

In [20]:
vendedores = ['Bruno Crispim', 'Gabriel  Bento']

df_analise_rep = df_analise[df_analise['user.name'].isin(vendedores)]

df_analise_rep

,id,name,amount_total,amount_unique,markup,created_at,closed_at,deal_custom_fields,last_activity_at,interactions,win,deal_stage.name,user.id,user.name,deal_lost_reason.name
12,6818bf0a03c9f10014ecc56b,NOP 109282-25 - UNIAO QUIMICA - VIRICAS I - 22...,7600.00,7600.00,future,2025-05-05T10:37:14.945-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
13,6818bea73d2c6e0027bdcc88,NCT-X 13965-25 - UNIAO QUIMICA - VIRICAS I - 2...,29000.00,29000.00,future,2025-05-05T10:35:35.514-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
14,6818baf8ef82eb002c8ee57c,NCT-X 13964-25 - UNIAO QUIMICA - VIRICAS I - 2...,30571.23,30571.23,future,2025-05-05T10:19:52.593-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
25,6817d7e69bf42000143ae859,NCT-X 8065-25 - JOULE - HOSPITAL ANIS RASSI - ...,478361.31,478361.31,future,2025-05-04T18:11:03.022-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,1,NaN,Negociação,651af445559e310016d78cfb,Gabriel Bento,NaN
26,6817cc312f87ea002799dc84,NCT-X 8072-25 - ELIAR - GMC (AM) - 24.03.2024 ...,70818.04,70818.04,future,2025-05-04T17:21:06.035-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,1,NaN,Negociação,651af445559e310016d78cfb,Gabriel Bento,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2721,677c3b699321820027e7d48c,NCI 3369-24 - CONNECTOR - MULTI CONSTRUTORA - ...,61000.00,61000.00,future,2025-01-06T17:22:01.459-03:00,2025-01-30T11:45:59.249-03:00,"[{'value': 'Representação', 'created_at': None...",NaN,4,0.0,Venda Perdida,6557ecc0295062000f0ac40a,Bruno Crispim,Preço (perca para produto inferior)
2722,677c394b7aa09300141393a6,NCD 0050-24 - SOUSAR CLIMAENGENHARIA - SQS 303...,78958.70,78958.70,future,2025-01-06T17:12:59.268-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,3,NaN,Orç. Enviar (Venda),6557ecc0295062000f0ac40a,Bruno Crispim,NaN
2723,677c3882a38d3a0018b260fc,NCD 25010141-24 - NORTHEC - SESI - 03.01.2025 ...,0.00,0.00,future,2025-01-06T17:09:38.197-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
2725,677c368ac1cc7300169f18eb,NCD 0049 -REV2- RENOVAR ENGENHARIA - CAIXA ECO...,0.00,0.00,future,2025-01-06T17:01:14.939-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Venda Ganha,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
2726,677c297d7741aa0017bb61db,NCT-X 7929-24 - GEOLAB - 27.12.2024 - GB,213706.80,213706.80,future,2025-01-06T16:05:33.845-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Conc. Em Andamento,651af445559e310016d78cfb,Gabriel Bento,NaN

In [21]:
def extrair_fator(campos):
    for campo in campos:
        if (
            isinstance(campo, dict)
            and campo.get("custom_field", {}).get("label") == "Fator"
        ):
            
            return campo["value"]
    return None





# Exemplo:
campos = [{'value': 'Representação', 'created_at': None, 'updated_at': None, 'custom_field_id': '653c112ed05921000f13b514', 'custom_field': {'_id': '653c112ed05921000f13b514', 'id': '653c112ed05921000f13b514', 'for': 'deal', 'label': 'Unidade de Negócio', 'order': 1, 'allow_new': False, 'required': True, 'type': 'option', 'unique': False, 'visible': True, 'created_at': '2023-10-27T16:36:14.477-03:00', 'updated_at': '2024-03-16T19:35:37.266-03:00'}}, 
{'value': 'NOP 109282-25', 'created_at': None, 'updated_at': None, 'custom_field_id': '654a2f3504fa9a001d3532e4', 'custom_field': {'_id': '654a2f3504fa9a001d3532e4', 'id': '654a2f3504fa9a001d3532e4', 'for': 'deal', 'label': 'Proposta Nº', 'order': 2, 'allow_new': False, 'required': True, 'type': 'text', 'unique': False, 'visible': True, 'created_at': '2023-11-07T09:36:05.667-03:00', 'updated_at': '2024-04-15T22:38:53.984-03:00'}},
 {'value': '0', 'created_at': None, 'updated_at': None, 'custom_field_id': '66154cc340f2800014e5a8d1', 'custom_field': {'_id': '66154cc340f2800014e5a8d1', 'id': '66154cc340f2800014e5a8d1', 'for': 'deal', 'label': 'Valor Sem Desconto', 'order': 3, 'allow_new': False, 'required': True, 'type': 'text', 'unique': False, 'visible': True, 'created_at': '2024-04-09T11:12:19.388-03:00', 'updated_at': '2024-04-09T11:12:40.077-03:00'}}, 
{'value': '1', 'created_at': None, 'updated_at': None, 'custom_field_id': '6614a914b72620001d624ed1', 'custom_field': {'_id': '6614a914b72620001d624ed1', 'id': '6614a914b72620001d624ed1', 'for': 'deal', 'label': 'Fator', 'order': 4, 'allow_new': False, 'required': True, 'type': 'text', 'unique': False, 'visible': True, 'created_at': '2024-04-08T23:33:56.530-03:00', 'updated_at': '2024-04-09T11:12:39.848-03:00'}}, 
{'value': 'VÍRICAS I', 'created_at': None, 'updated_at': None, 'custom_field_id': '65373df357adae0012acf942', 'custom_field': {'_id': '65373df357adae0012acf942', 'id': '65373df357adae0012acf942', 'for': 'deal', 'label': 'Nome da Obra', 'order': 5, 'allow_new': False, 'required': True, 'type': 'text', 'unique': False, 'visible': True, 'created_at': '2023-10-24T00:45:55.120-03:00', 'updated_at': '2024-04-09T11:12:39.861-03:00'}},
 {'value': 'Obra Nova', 'created_at': None, 'updated_at': None, 'custom_field_id': '65373e3a8b08220014741db2', 'custom_field': {'_id': '65373e3a8b08220014741db2', 'id': '65373e3a8b08220014741db2', 'for': 'deal', 'label': 'Tipo de Obra', 'order': 6, 'allow_new': False, 'required': True, 'type': 'option', 'unique': False, 'visible': True, 'created_at': '2023-10-24T00:47:06.105-03:00', 'updated_at': '2024-04-09T11:12:39.876-03:00'}}, {'value': 'Brasília', 'created_at': None, 'updated_at': None, 'custom_field_id': '6511f4a2c18469001aca4dd3', 'custom_field': {'_id': '6511f4a2c18469001aca4dd3', 'id': '6511f4a2c18469001aca4dd3', 'for': 'deal', 'label': 'Local da Obra (Cidade)', 'order': 7, 'allow_new': False, 'required': True, 'type': 'text', 'unique': False, 'visible': True, 'created_at': '2023-09-25T17:59:14.250-03:00', 'updated_at': '2024-04-15T22:50:43.126-03:00'}}, {'value': 'Distrito Federal (DF)', 'created_at': None, 'updated_at': None, 'custom_field_id': '65f613cc0e75900020da0ccf', 'custom_field': {'_id': '65f613cc0e75900020da0ccf', 'id': '65f613cc0e75900020da0ccf', 'for': 'deal', 'label': 'Local da Obra (Estado)', 'order': 8, 'allow_new': False, 'required': True, 'type': 'option', 'unique': False, 'visible': True, 'created_at': '2024-03-16T18:49:00.281-03:00', 'updated_at': '2024-04-15T22:51:04.162-03:00'}}, {'value': ['N/A'], 'created_at': None, 'updated_at': None, 'custom_field_id': '6511ebfe0f01700012e1574e', 'custom_field': {'_id': '6511ebfe0f01700012e1574e', 'id': '6511ebfe0f01700012e1574e', 'for': 'deal', 'label': 'Produtos (Distribuição)', 'order': 9, 'allow_new': False, 'required': True, 'type': 'multiple_choice', 'unique': False, 'visible': True, 'created_at': '2023-09-25T17:22:22.338-03:00', 'updated_at': '2024-10-13T19:38:49.319-03:00'}}, {'value': ['VENTILAÇÃO/EXAUSTÃO'], 'created_at': None, 'updated_at': None, 'custom_field_id': '653c132df65790000dc55a25', 'custom_field': {'_id': '653c132df65790000dc55a25', 'id': '653c132df65790000dc55a25', 'for': 'deal', 'label': 'Produtos (Representação)', 'order': 10, 'allow_new': False, 'required': True, 'type': 'multiple_choice', 'unique': False, 'visible': True, 'created_at': '2023-10-27T16:44:45.176-03:00', 'updated_at': '2024-10-13T19:42:04.019-03:00'}}, {'value': ['N/A'], 'created_at': None, 'updated_at': None, 'custom_field_id': '65f619ae61ecc800180b9b64', 'custom_field': {'_id': '65f619ae61ecc800180b9b64', 'id': '65f619ae61ecc800180b9b64', 'for': 'deal', 'label': 'ArControl', 'order': 11, 'allow_new': False, 'required': True, 'type': 'multiple_choice', 'unique': False, 'visible': True, 'created_at': '2024-03-16T19:14:06.997-03:00', 'updated_at': '2024-04-09T11:12:39.953-03:00'}}, {'value': None, 'created_at': None, 'updated_at': None, 'custom_field_id': '65373f8e7841c200107f137f', 'custom_field': {'_id': '65373f8e7841c200107f137f', 'id': '65373f8e7841c200107f137f', 'for': 'deal', 'label': 'Previsão do Resultado da Concorrência', 'order': 12, 'allow_new': False, 'required': True, 'type': 'date', 'unique': False, 'visible': True, 'created_at': '2023-10-24T00:52:46.533-03:00', 'updated_at': '2024-04-09T11:12:39.970-03:00'}}, {'value': 'PROJELMEC', 'created_at': None, 'updated_at': None, 'custom_field_id': '6565f1481bef6200125c4f3e', 'custom_field': {'_id': '6565f1481bef6200125c4f3e', 'id': '6565f1481bef6200125c4f3e', 'for': 'deal', 'label': 'Fábrica (Representação)', 'order': 13, 'allow_new': False, 'required': True, 'type': 'option', 'unique': False, 'visible': True, 'created_at': '2023-11-28T10:55:20.952-03:00', 'updated_at': '2024-10-13T19:28:49.994-03:00'}}, {'value': None, 'created_at': None, 'updated_at': None, 'custom_field_id': '65373f2c67280700253cc49b', 'custom_field': {'_id': '65373f2c67280700253cc49b', 'id': '65373f2c67280700253cc49b', 'for': 'deal', 'label': 'Data Limite para Recebimento do Produto na Obra', 'order': 14, 'allow_new': False, 'required': True, 'type': 'date', 'unique': False, 'visible': True, 'created_at': '2023-10-24T00:51:08.322-03:00', 'updated_at': '2024-04-15T22:53:07.885-03:00'}}, {'value': '25%', 'created_at': None, 'updated_at': None, 'custom_field_id': '65f6376d66ff5f0012a51212', 'custom_field': {'_id': '65f6376d66ff5f0012a51212', 'id': '65f6376d66ff5f0012a51212', 'for': 'deal', 'label': 'Chance de Ganho', 'order': 15, 'allow_new': False, 'required': True, 'type': 'option', 'unique': False, 'visible': True, 'created_at': '2024-03-16T21:21:02.003-03:00', 'updated_at': '2024-04-09T11:12:40.021-03:00'}}, {'value': None, 'created_at': None, 'updated_at': None, 'custom_field_id': '6581efd19a0286000dd1b949', 'custom_field': {'_id': '6581efd19a0286000dd1b949', 'id': '6581efd19a0286000dd1b949', 'for': 'deal', 'label': 'Previsão de Fechamento da Negociação', 'order': 16, 'allow_new': False, 'required': True, 'type': 'date', 'unique': False, 'visible': True, 'created_at': '2023-12-19T16:32:33.914-03:00', 'updated_at': '2024-04-17T11:44:30.425-03:00'}}, {'value': 'Arthur Maciel', 'created_at': None, 'updated_at': None, 'custom_field_id': '6553765fba8001000f8377c8', 'custom_field': {'_id': '6553765fba8001000f8377c8', 'id': '6553765fba8001000f8377c8', 'for': 'deal', 'label': 'Orçamentista', 'order': 17, 'allow_new': False, 'required': True, 'type': 'option', 'unique': False, 'visible': True, 'created_at': '2023-11-14T10:30:07.694-03:00', 'updated_at': '2024-10-16T22:35:05.512-03:00'}}, {'value': '', 'created_at': None, 'updated_at': None, 'custom_field_id': '65f62ea405be7d000dfb2c04', 'custom_field': {'_id': '65f62ea405be7d000dfb2c04', 'id': '65f62ea405be7d000dfb2c04', 'for': 'deal', 'label': 'NPS - Como o Cliente avalia o atendimento', 'order': 18, 'allow_new': False, 'required': True, 'type': 'option', 'unique': False, 'visible': True, 'created_at': '2024-03-16T20:43:32.462-03:00', 'updated_at': '2024-04-15T22:59:08.487-03:00'}}]


fator = extrair_fator(campos)
print(fator)  # vai imprimir '1'

1

In [28]:
import ast

def parse_custom_fields(s):
    if isinstance(s, str):
        try:
            return ast.literal_eval(s)
        except (ValueError, SyntaxError):
            return None
    return s

# Atribuição com .loc para evitar o warning
df_analise_rep.loc[:, "deal_custom_fields"] = df_analise_rep["deal_custom_fields"].apply(parse_custom_fields)


print(df_analise_rep["deal_custom_fields"].apply(type).value_counts())

deal_custom_fields
<class 'list'>    260
Name: count, dtype: int64

In [31]:
import ast
import pandas as pd

# 1) Carregue seu DataFrame

# 2) Converter strings para listas de dicionários
def parse_custom_fields(s):
    if isinstance(s, str):
        try:
            return ast.literal_eval(s)
        except (ValueError, SyntaxError):
            return []
    elif isinstance(s, list):
        return s
    else:
        return []

df.loc[:, "deal_custom_fields"] = df["deal_custom_fields"].apply(parse_custom_fields)

# 3) Função que extrai o valor de “Fator”
def extrair_fator(campos):
    for campo in campos:
        cf = campo.get("custom_field", {})
        if cf.get("label", "").strip().lower() == "fator":
            return campo.get("value")
    return None

# 4) Aplique linha a linha e crie a coluna 'fator'
df.loc[:, "fator"] = df["deal_custom_fields"].apply(extrair_fator)

# 5) (Opcional) Converter string com vírgula para float
df.loc[:, "fator"] = (
    df["fator"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float, errors="ignore")
)

# 6) Filtrar só Bruno Crispim e Gabriel Bento e mostrar
vendedores = ["Bruno Crispim", "Gabriel  Bento"]
resultado = df[df["user.name"].isin(vendedores)][["id", "user.name", "fator"]]
print(resultado.head(20))

                           id       user.name   fator
12   6818bf0a03c9f10014ecc56b   Bruno Crispim       1
13   6818bea73d2c6e0027bdcc88   Bruno Crispim       1
14   6818baf8ef82eb002c8ee57c   Bruno Crispim       1
25   6817d7e69bf42000143ae859  Gabriel  Bento    0.73
26   6817cc312f87ea002799dc84  Gabriel  Bento     0.6
27   6817cae7ae9fbd00148d8060  Gabriel  Bento       1
28   6817c9e49bf42000273ae212  Gabriel  Bento     0.8
29   6817c8d6473aea00174b1f1f  Gabriel  Bento       1
37   681510ed06910f0014cb7098   Bruno Crispim     0.7
53   6812921d25f0cc0025342649  Gabriel  Bento     0.6
54   6812920cbded940014949eaa  Gabriel  Bento     0.6
93   68113ad73bd702001493746d   Bruno Crispim     0.8
101  6811391ea12f2600210eda82   Bruno Crispim     0.8
146  6810e0be6f2584001be8d1b2  Gabriel  Bento    0.54
147  6810e0adaa4450001448da7f  Gabriel  Bento    0.54
149  6810dfdf3790f200141ec0c9  Gabriel  Bento  0.5632
150  6810dfca1e72e5001d89495a  Gabriel  Bento  0.5632
219  680f6e0532793a001a0156e7   Bruno Crispim    0.64
221  680e8856865508001406230f  Gabriel  Bento       1
222  680e883da2b2b4001455a9cf  Gabriel  Bento       1

In [26]:
for custom_field in df_analise_rep['deal_custom_fields']:
    campos = [custom_field]
    print(type(campos))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>

In [22]:
df_analise_rep

,id,name,amount_total,amount_unique,markup,created_at,closed_at,deal_custom_fields,last_activity_at,interactions,win,deal_stage.name,user.id,user.name,deal_lost_reason.name
12,6818bf0a03c9f10014ecc56b,NOP 109282-25 - UNIAO QUIMICA - VIRICAS I - 22...,7600.00,7600.00,future,2025-05-05T10:37:14.945-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
13,6818bea73d2c6e0027bdcc88,NCT-X 13965-25 - UNIAO QUIMICA - VIRICAS I - 2...,29000.00,29000.00,future,2025-05-05T10:35:35.514-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
14,6818baf8ef82eb002c8ee57c,NCT-X 13964-25 - UNIAO QUIMICA - VIRICAS I - 2...,30571.23,30571.23,future,2025-05-05T10:19:52.593-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
25,6817d7e69bf42000143ae859,NCT-X 8065-25 - JOULE - HOSPITAL ANIS RASSI - ...,478361.31,478361.31,future,2025-05-04T18:11:03.022-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,1,NaN,Negociação,651af445559e310016d78cfb,Gabriel Bento,NaN
26,6817cc312f87ea002799dc84,NCT-X 8072-25 - ELIAR - GMC (AM) - 24.03.2024 ...,70818.04,70818.04,future,2025-05-04T17:21:06.035-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,1,NaN,Negociação,651af445559e310016d78cfb,Gabriel Bento,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2721,677c3b699321820027e7d48c,NCI 3369-24 - CONNECTOR - MULTI CONSTRUTORA - ...,61000.00,61000.00,future,2025-01-06T17:22:01.459-03:00,2025-01-30T11:45:59.249-03:00,"[{'value': 'Representação', 'created_at': None...",NaN,4,0.0,Venda Perdida,6557ecc0295062000f0ac40a,Bruno Crispim,Preço (perca para produto inferior)
2722,677c394b7aa09300141393a6,NCD 0050-24 - SOUSAR CLIMAENGENHARIA - SQS 303...,78958.70,78958.70,future,2025-01-06T17:12:59.268-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,3,NaN,Orç. Enviar (Venda),6557ecc0295062000f0ac40a,Bruno Crispim,NaN
2723,677c3882a38d3a0018b260fc,NCD 25010141-24 - NORTHEC - SESI - 03.01.2025 ...,0.00,0.00,future,2025-01-06T17:09:38.197-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Consulta Enviada,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
2725,677c368ac1cc7300169f18eb,NCD 0049 -REV2- RENOVAR ENGENHARIA - CAIXA ECO...,0.00,0.00,future,2025-01-06T17:01:14.939-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Venda Ganha,6557ecc0295062000f0ac40a,Bruno Crispim,NaN
2726,677c297d7741aa0017bb61db,NCT-X 7929-24 - GEOLAB - 27.12.2024 - GB,213706.80,213706.80,future,2025-01-06T16:05:33.845-03:00,NaN,"[{'value': 'Representação', 'created_at': None...",NaN,0,NaN,Conc. Em Andamento,651af445559e310016d78cfb,Gabriel Bento,NaN